baseURL = "https://tech-andgar.me/"
title = "TECH-ANDGAR"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
canonifyURLs = true

pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "andgar2010"
[params]
author = "Andrés García"
description = "Andrés García's personal website"
keywords = "blog,developer,personal"
info = "Developer Full Stack App Mobile Flutter"
avatarURL = "images/avatar.jpg"
#gravatar = "dev@tech-andgar.me"
footercontent = "H E L L O @ T E C H - A N D G A R . M E"
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = true
hideCopyright = false
since = 2020

# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"

# Right To Left, shift content direction for languagues such as Arabic
rtl = false

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false

# Series see also post count
maxSeeAlsoItems = 5

# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []

# Custom SCSS
customSCSS = []

# Custom JS
customJS = []
# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
[params.googleTagManager]
id = "UA-33194632-1"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive - defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fab fa-github"
weight = 1
url = "https://link.tech-andgar.me/github"

# [[params.social]]
# name = "Gitlab"
# icon = "fab fa-gitlab"
# weight = 2
# # url = "https://gitlab.com/andgar2010/"

# [[params.social]]
# name = "Twitter"
# icon = "fab fa-twitter"
# weight = 3
# # url = "https://twitter.com/andgar2010/"

[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin"
weight = 4
url = "https://link.tech-andgar.me/linkedin"

# [[params.social]]
# name = "Medium"
# icon = "fab fa-medium"
# weight = 5
# url = "https://medium.com/@andgar2010"

# [[params.social]]
# name = "RSS"
# icon = "fas fa-rss"
# weight = 6
# url = "https://tech-andgar.me/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

#[[params.social]]
# name = "RSS"
# icon = "fas fa-rss"
# weight = 6
# url = "http://bit.ly/CertiSololearn-AndGar"
# rel = "alternate"
# type = "application/rss+xml"

[languages]

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[[languages.en.menu.main]]
name = "CV"
weight = 6
url = "https://link.tech-andgar.me/CV-AFGR-DEV"

[languages.es-419]
languagename = ":spain:"
title = "TECH-ANDGAR"

[languages.es-419.params]
author = "Andrés García"
info = "Desarrollador Full Stack App Movil Flutter"
description = "Sítio personal de Andrés García"
keywords = "blog,desarrollador,personal"
footercontent = "H E L L O @ T E C H - A N D G A R . M E"

[languages.es-419.menu]

[[languages.es-419.menu.main]]
name = "Acerca de"
weight = 1
url = "about/"

[[languages.es-419.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.es-419.menu.main]]
name = "Proyectos"
weight = 3
url = "projects/"

[[languages.es-419.menu.main]]
name = "Contacto"
weight = 5
url = "contact/"

[[languages.es-419.menu.main]]
name = "CV"
weight = 6
url = "https://link.tech-andgar.me/HV-AFGR-DEV"


#    [languages.pt-br]
#        languagename = "Português"
#        title = "TECH-ANDGAR"
#
#        [languages.pt-br.params]
#            author = "Andrés García"
#            info = "Full Stack DevOps e Mágico"
#            description = "Sítio pessoal de Andrés García"
#            keywords = "blog,desenvolvedor,personal"
#            footercontent = "H E L L O @ T E C H - A N D G A R . M E"
#
#        [languages.pt-br.menu]
#
#            [[languages.pt-br.menu.main]]
#            name = "Sobre"
#            weight = 1
#            url = "about/"
#
#            [[languages.pt-br.menu.main]]
#            name = "Blog"
#            weight = 2
#            url = "posts/"
#
#            [[languages.pt-br.menu.main]]
#            name = "Projetos"
#            weight = 3
#            url = "projects/"
#
#            [[languages.pt-br.menu.main]]
#            name = "Contato"
#            weight = 5
#            url = "contact/"
#