baseURL = "https://tech-andgar.me/"
languagecode = "en"
title = "TECH-ANDGAR"
theme = "hugo-coder"

defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "andgar2010"

googleAnalytics = "UA-33194632-1"

[params]
    images = ["images/avatar.jpg"]
    author = "Andrés García"
    description = "Andrés García's personal website"
    keywords = "blog,developer,personal"
    info = "Developer Full Stack and App Mobile"
    avatarurl = "images/avatar.jpg"
    #gravatar = "dev@tech-andgar.me"
    footercontent = "H E L L O @ T E C H - A N D G A R . M E"

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# # If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#     siteID = "ABCDE"
#     # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://link.tech-andgar.me/github"
#[[params.social]]
#    name = "Gitlab"
#    icon = "fab fa-gitlab"
#    weight = 2
#    url = "https://gitlab.com/andgar2010/"
#[[params.social]]
#    name = "Twitter"
#    icon = "fab fa-twitter"
#    weight = 3
#    url = "https://twitter.com/andgar2010/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://link.tech-andgar.me/linkedin"
#[[params.social]]
#    name = "Medium"
#    icon = "fab fa-medium"
#    weight = 5
#    url = "https://medium.com/@andgar2010"
#[[params.social]]
#    name = "RSS"
#    icon = "fas fa-rss"
#    weight = 6
#    url = "https://tech-andgar.me/index.xml"
#    rel = "alternate"
#    type = "application/rss+xml"
#[[params.social]]
#    name = "RSS"
#    icon = "fas fa-rss"
#    weight = 6
#    url = "http://bit.ly/CertiSololearn-AndGar"
#    rel = "alternate"
#    type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"

            [[languages.en.menu.main]]
            name = "CV"
            weight = 6
            url = "https://link.tech-andgar.me/CV-AFGR-DEV"


    [languages.es-419]
        languagename = "Español"
        title = "TECH-ANDGAR"

        [languages.es-419.params]
            author = "Andrés García"
            info = "Desarrollador Full Stack y App Movil"
            description = "Sítio personal de Andrés García"
            keywords = "blog,desarrollador,personal"
            footercontent = "H E L L O @ T E C H - A N D G A R . M E"

        [languages.es-419.menu]

            [[languages.es-419.menu.main]]
            name = "Acerca de"
            weight = 1
            url = "about/"

            [[languages.es-419.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.es-419.menu.main]]
            name = "Proyectos"
            weight = 3
            url = "projects/"

            [[languages.es-419.menu.main]]
            name = "Contacto"
            weight = 5
            url = "contact/"

            [[languages.es-419.menu.main]]
            name = "CV"
            weight = 6
            url = "https://link.tech-andgar.me/HV-AFGR-DEV"


#    [languages.pt-br]
#        languagename = "Português"
#        title = "TECH-ANDGAR"
#
#        [languages.pt-br.params]
#            author = "Andrés García"
#            info = "Full Stack DevOps e Mágico"
#            description = "Sítio pessoal de Andrés García"
#            keywords = "blog,desenvolvedor,personal"
#            footercontent = "H E L L O @ T E C H - A N D G A R . M E"
#
#        [languages.pt-br.menu]
#
#            [[languages.pt-br.menu.main]]
#            name = "Sobre"
#            weight = 1
#            url = "about/"
#
#            [[languages.pt-br.menu.main]]
#            name = "Blog"
#            weight = 2
#            url = "posts/"
#
#            [[languages.pt-br.menu.main]]
#            name = "Projetos"
#            weight = 3
#            url = "projects/"
#
#            [[languages.pt-br.menu.main]]
#            name = "Contato"
#            weight = 5
#            url = "contact/"
#